const userForm = {
  name: {
    label: 'Name',
    placeholder: 'Enter name',
    required: true,
    fieldType: 'textfield',
    validationType: null,
    value: '',
    hasError: false,
    error: '',
    dirty: false,
  },
  email: {
    label: 'Email address',
    placeholder: 'Enter email address',
    required: true,
    fieldType: 'textfield',
    validationType: 'email',
    value: '',
    hasError: false,
    error: '',
    dirty: false,
  },
  phone: {
    label: 'Phone',
    placeholder: 'Enter phone',
    required: true,
    fieldType: 'textfield',
    validationType: 'phone',
    value: '',
    hasError: false,
    error: '',
    dirty: false,
  },
  address: {
    label: 'Address',
    placeholder: 'Enter address',
    required: true,
    fieldType: 'textfield',
    validationType: null,
    value: '',
    hasError: false,
    error: '',
    dirty: false,
  },
  company: {
    label: 'Company',
    placeholder: 'Enter company',
    required: true,
    fieldType: 'textfield',
    validationType: null,
    value: '',
    hasError: false,
    error: '',
    dirty: false,
  },
};

export default userForm;
